cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --clusters={resources.cluster}
    -n {threads}
    --mem-per-cpu={resources.mem_mb_per_cpu}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    -A lp_jm_virome_group
    -t {resources.runtime}
    -N 1
    # $(./parseJobID.sh {dependencies})
default-resources:
  - cluster=genius
  - mem_mb_per_cpu=3400
  - runtime=100
set-resources:
  - ska_fastq:mem_mb_per_cpu=28000
  - ska_distance:mem_mb_per_cpu=28000
  - ska_distance:runtime=5
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
jobscript: jobscript_template.sh
cluster-cancel: 'scancel'
immediate-submit: False
notemp: False
groups:
  - ska_distance=group1
group-components:
  - group1=625
